//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.UI;

namespace WebUI
{
	public partial class Default
	{
		
		protected System.Web.UI.WebControls.Button button1;
	}
}

